In [1]:
import matplotlib as mpl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Info binária filmes

In [2]:
# Sim = 1
# Não = 0

In [3]:
terror    = np.array([1, 0, 0, 0, 0, 0, 0, 1])
suspense  = np.array([1, 1, 1, 0, 0, 0, 1, 1])
drama     = np.array([1, 1, 1, 0, 1, 0, 1, 1])

print("\n", terror, "\n",suspense, "\n",drama)


 [1 0 0 0 0 0 0 1] 
 [1 1 1 0 0 0 1 1] 
 [1 1 1 0 1 0 1 1]


In [4]:
sum_terror = terror.sum()
sum_suspen = suspense.sum()
sum_drama  = drama.sum()
n          = terror.size

print(sum_terror, sum_suspen, sum_drama)

2 5 6


In [5]:
n

8

In [6]:
pc_terror = (sum_terror/n)*100
pc_suspen = (sum_suspen/n)*100
pc_drama  = (sum_drama/n)*100

# https://python-course.eu/python-tutorial/formatted-output.php
print("Terror: %4.2f, Suspense: %4.2f, Drama: %4.2f," % (pc_terror, pc_suspen, pc_drama))

Terror: 25.00, Suspense: 62.50, Drama: 75.00,


In [7]:
pc_terror2 = terror.mean()*100
pc_suspen2 = suspense.mean()*100
pc_drama2  = drama.mean()*100

print("Terror: %4.2f, Suspense: %4.2f, Drama: %4.2f," % (pc_terror2, pc_suspen2, pc_drama2))

Terror: 25.00, Suspense: 62.50, Drama: 75.00,


# Medidas de posição e dispersão

In [ ]:
shape1, scale1 = 1, 4
ex_list1 = np.random.gamma(shape1, scale1, 100)

plt.figure()
sns.displot(x = ex_list1, fill = True, kind = "kde")

In [ ]:
ex_list1.round(2)

In [ ]:
shape2, scale2 = 20, 0.5 
ex_list2 = np.random.gamma(shape2, scale2, 100)

plt.figure()
sns.displot(x = ex_list2, fill = True, kind = "kde")

In [ ]:
ex_list2.round(2)

# Média

In [ ]:
print(ex_list1.mean().round(2), ex_list2.mean().round(2))

#Mediana

In [ ]:
print(np.median(ex_list1).round(2), np.median(ex_list2).round(2))